---
name: CGI-Session-Driver-odbc
version: 1.00
author:
  - Ron Savage <ron@savage.net.au>
abstract: A CGI::Session driver for ODBC
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  CGI::Session::Driver::DBI: 0
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  CGI::Session::Driver::odbc:
    file: lib/CGI/Session/Driver/odbc.pm
    version: 1.00
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
